//
//  AuthViewModel.swift
//  FernHealthChallenge
//
//  Created by Arturo Reyes on 6/20/20.
//  Copyright © 2020 Arturo Reyes. All rights reserved.
//

import Foundation
import Combine

/// An enum for the possible outputs from different codes
enum CodeValue: Int {
    // Code is valid
    case valid = 200
    // Code is not recognized
    case invalid = 404
    // Code for when the program is full
    case fullProgram = 400
    
    // The localized string key of the error description to be shown to the user for each code value
    var descriptionKey: String {
        switch self {
        case .invalid    : return "invalid_code_message"
        case .fullProgram: return "full_program_message"
        default: return ""
        }
    }
}

/// The ViewModel for the CodeValidatorViewController
final class CodeAuthViewModel {
    
    // The code string input by the user
    @Published var code: String = ""
    // The code value generated by the code string
    @Published private(set) var codeValue: CodeValue?
    
    var didCompleteRequest: ((Subscribers.Completion<Error>) -> Void)?
    
    private var token: AnyCancellable?
    // The code validator service that converts the code string into a code value
    let codeValidator: CodeAuthenticator
    
    
    init(codeValidator: CodeAuthenticator) {
        self.codeValidator = codeValidator
    }
    
    /// Validate the code
    func authenticate() {
        guard let completion = didCompleteRequest else { return }
        
        token = codeValidator.authenticate(code).sink(
            receiveCompletion: completion,
            receiveValue: { [weak self] value in
                guard let self = self else { return }
                guard let value = value else { return }
                self.codeValue = value
            })
        
    }
}
